# Generated by Django 3.1.2 on 2022-04-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItems',
        ),
    ]
