# Generated by Django 3.1.2 on 2022-05-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-transaction_id', '-id']},
        ),
    ]
