# Generated by Django 4.0.4 on 2022-05-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_cartitem_product_cartitem_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='products',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
