# Generated by Django 4.0.4 on 2022-05-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_cartitem_products_cartitem_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
    ]
