# Generated by Django 4.0.4 on 2022-05-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_rename_products_cartitem_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('customer', 'product')},
        ),
    ]
