# Generated by Django 4.0.4 on 2022-05-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'transaction_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
