# Generated by Django 4.0.4 on 2022-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='edited_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
