# Generated by Django 4.0.4 on 2022-05-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_productreview_edited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='default_add',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
