# Generated by Django 4.0.4 on 2022-05-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_address_shippingaddress_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='skills_and_learnings',
            field=models.TextField(blank=True, null=True),
        ),
    ]
