# Generated by Django 4.0.4 on 2022-05-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'product')},
        ),
    ]
