# Generated by Django 4.0.4 on 2022-05-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_contactus_gift_alter_blog_slug_giftimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-sent_on'], 'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='sent_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
