# Generated by Django 4.0.4 on 2022-05-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_contactus_options_contactus_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
