# Generated by Django 4.0.4 on 2022-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_gift_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
