# Generated by Django 4.0.4 on 2022-05-19 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_order_shipping_method_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='start_date',
        ),
    ]
