# Generated by Django 4.0.4 on 2022-05-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_blog_image_link_productimage_image_link_subsciber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsciber',
            name='customer',
        ),
        migrations.AddField(
            model_name='giftimage',
            name='image_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='subsciber',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
