# Generated by Django 4.0.4 on 2022-05-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_remove_subsciber_customer_giftimage_image_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
    ]
