# Generated by Django 4.0.4 on 2022-05-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_notificationsend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsend',
            name='title',
        ),
        migrations.AddField(
            model_name='notificationsend',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notificationsend',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
