# Generated by Django 4.0.4 on 2022-05-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_notificationsend_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciber',
            new_name='Subscriber',
        ),
    ]
