# Generated by Django 4.0.4 on 2022-06-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_rename_complete_order_ordered_order_out_for_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arriving_today',
            field=models.BooleanField(default=False),
        ),
    ]
