# Generated by Django 4.0.4 on 2022-06-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_order_arriving_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
