# Generated by Django 4.0.4 on 2022-06-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_order_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='in_stock',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='mega_menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='real_life_connect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='skills_and_learnings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='strip_menu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gift',
            name='technical_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
