# Generated by Django 4.0.4 on 2022-06-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='returned',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
