# Generated by Django 4.0.4 on 2022-06-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_remove_order_returned_orderitem_refunded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.coupon'),
        ),
    ]
