# Generated by Django 4.0.4 on 2022-06-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_shippingaddress_first_name_shippingaddress_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
    ]
