# Generated by Django 4.0.4 on 2022-06-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_remove_shippingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('address_1', 'address_1')},
        ),
    ]
