# Generated by Django 4.0.4 on 2022-06-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_shippingaddress_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='returned_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
