# Generated by Django 4.0.4 on 2022-06-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_productcontactus_giftcontactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcontactus',
            name='message',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='productcontactus',
            name='message',
            field=models.TextField(null=True, unique=True),
        ),
    ]
