# Generated by Django 4.0.4 on 2022-06-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_remove_giftcontactus_product_giftcontactus_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcontactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productcontactus',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
