# Generated by Django 4.0.4 on 2022-06-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcontactus',
            name='quantity',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productcontactus',
            name='quantity',
            field=models.CharField(max_length=500),
        ),
    ]
