# Generated by Django 4.0.4 on 2022-06-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_order_amount_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_paid',
            new_name='amount',
        ),
    ]
